#!/bin/bash
rm -rf ~/rpmbuild
rm -rf REPO/*
mkdir -p  ~/rpmbuild  
echo "Generating devOS rpm"
cp -r devOS/* ~/rpmbuild/
cd  ~/rpmbuild
rpmbuild --target noarch -ba spec/utils.spec
cd -
cp  /root/rpmbuild/RPMS/noarch/devOS*.noarch.rpm REPO
cp bin/* REPO
createrepo REPO
rsync  -r --delete REPO/* /var/www/html/REPO/ --progress

#cp ~/rpmbuild/SRPMS/*.rpm ../../rpms/
