name = "devOS"
description = "devOS"
version = "0.0.7"
modules = []
groups = []

[customizations]
hostname = "devOS"

[[packages]]
name = "nmap"
version = "*"

[[packages]]
name = "rsync"
version = "*"

[[packages]]
name = "devOS"
version = "*"

[[packages]]
name = "openssh"
version = "*"

[[packages]]
name = "grub2-pc"
version = "*"

[[packages]]
name = "htop"
version = "*"

[[packages]]
name = "python3-ifcfg"
version = "*"


[[packages]]
name = "httpd"
version = "*"

[[packages]]
name = "epel-release"
version = "*"

[customizations.timezone]
timezone = "Europe/Berlin"

[customizations.locale]
languages = ["de_DE.UTF-8"]
keyboard = "de"

[customizations.services]
enabled = ["httpd"]
disabled = ["kdump"]

[customizations.firewall]
ports = ["22:tcp", "80:tcp"]

