name = "devOS"
description = "devOS"
version = "0.0.5"
modules = []
groups = []

[customizations]
hostname = "devOS"

[customizations.timezone]
timezone = "Europe/Berlin"

[customizations.locale]
languages = ["de_DE.UTF-8"]
keyboard = "de"

[customizations.firewall]
ports = ["22:tcp", "80:tcp"]

[customizations.services]
enabled = ["cockpit.socket", "httpd"]
disabled = ["kdump"]



[[packages]]
name = "epel-release"
version = "*"

[[packages]]
name = ["htop","httpd"]
version = "*"

[[packages]]
name = "python3-ifcfg"
version = "*"

[[packages]]
name = "nmap"
version = "*"

[[packages]]
name = "devOS"
version = "*"

[[packages]]
name = "openssh"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "rsync"
version = "*"

[[packages]]
name = "epel-release"
version = "*"



