{
    "errors": [],
    "sources": {
        "devOS": {
            "check_gpg": false,
            "check_ssl": false,
            "gpgkey_urls": [
                "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
            ],
            "name": "devOS",
            "system": true,
            "type": "baseurl",
            "url": "http://10.2.2.12/REPO/"
        }
    }
}

