name = "devOS"
description = "devOS"
version = "0.0.5"
modules = []
groups = []

[[packages]]
name = "anaconda"
version = "*"

[[packages]]
name = "devOS"
version = "*"

[[packages]]
name = "epel-release"
version = "*"

[[packages]]
name = "epel-release"
version = "*"

[[packages]]
name = "nmap"
version = "*"

[[packages]]
name = "openssh"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "rsync"
version = "*"

[customizations]
hostname = "devOS"

[customizations.timezone]
timezone = "Europe/Berlin"
