name = "devOS"
description = "devOS"
version = "0.0.6"
modules = []
groups = []

[[packages]]
name = "devOS"
version = "*"

[[packages]]
name = "epel-release"
version = "*"

[[packages]]
name = "epel-release"
version = "*"

[[packages]]
name = "htop"
version = "*"

[[packages]]
name = "nmap"
version = "*"

[[packages]]
name = "openssh"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "python3-ifcfg"
version = "*"

[[packages]]
name = "rsync"
version = "*"

[customizations]
hostname = "devOS"

[customizations.timezone]
timezone = "Europe/Berlin"

[customizations.locale]
languages = ["de_DE.UTF-8"]
keyboard = "de"
